[theme]
base = "light"
primaryColor = "#fee600"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f8f9fa"
textColor = "#2b2d33"
font = "'Space Grotesk':https://fonts.googleapis.com/css2?family=Space+Grotesk:wght@300..700&display=swap"

[server]
enableXsrfProtection = false